### ISSUE TITLE
Замечания по RotateByte

### ISSUE THREAD

**Issue by alexey-malov** [Ginyola/oop#1]
https://github.com/Ginyola/oop/blob/45c4ab20d2ccf1fe1882cf5ba5f34996c7566409/lw1/rotatebyte/rotatebyte.cpp#L40-L45

- [x] Не используйте atoi, она не сообщает об ошибке. Используйте std::stoi

**Comment by alexey-malov** [comment]
https://github.com/Ginyola/oop/blob/45c4ab20d2ccf1fe1882cf5ba5f34996c7566409/lw1/rotatebyte/rotatebyte.cpp#L33-L43

- [ ] Вместо именованной константы лучше использовать число, т.к. константа далеко объявлена от фактически используемых индексов.

**Comment by alexey-malov** [comment]
- [ ] Выделить функцию, выполняющую циклическое вращение байта влево на заданное количество разрядов и вправо:
```
uint8_t RotateByteLeft(uint8_t b, unsigned numberOfBits);
uint8_t RotateByteRight(uint8_t b, unsigned numberOfBits);
```

**Comment by alexey-malov** [comment]
- [ ] Программа должна вращать байт, состоящий из 8 бит

**Comment by Ginyola** [comment]
Замечания поправил
